# This is a copy of <PICO_PLAYGROUND_PATH>/external/PICO_PLAYGROUND_import.cmake

# This can be dropped into an external project to help locate pico-extras
# It should be include()ed prior to project()

if (DEFINED ENV{PICO_PLAYGROUND_PATH} AND (NOT PICO_PLAYGROUND_PATH))
    set(PICO_PLAYGROUND_PATH $ENV{PICO_PLAYGROUND_PATH})
    message("Using PICO_PLAYGROUND_PATH from environment ('${PICO_PLAYGROUND_PATH}')")
endif ()

if (DEFINED ENV{PICO_PLAYGROUND_FETCH_FROM_GIT} AND (NOT PICO_PLAYGROUND_FETCH_FROM_GIT))
    set(PICO_PLAYGROUND_FETCH_FROM_GIT $ENV{PICO_PLAYGROUND_FETCH_FROM_GIT})
    message("Using PICO_PLAYGROUND_FETCH_FROM_GIT from environment ('${PICO_PLAYGROUND_FETCH_FROM_GIT}')")
endif ()

if (DEFINED ENV{PICO_PLAYGROUND_FETCH_FROM_GIT_PATH} AND (NOT PICO_PLAYGROUND_FETCH_FROM_GIT_PATH))
    set(PICO_PLAYGROUND_FETCH_FROM_GIT_PATH $ENV{PICO_PLAYGROUND_FETCH_FROM_GIT_PATH})
    message("Using PICO_PLAYGROUND_FETCH_FROM_GIT_PATH from environment ('${PICO_PLAYGROUND_FETCH_FROM_GIT_PATH}')")
endif ()



set(PICO_PLAYGROUND_PATH "${PICO_PLAYGROUND_PATH}" CACHE PATH "Path to the PICO EXTRAS")
set(PICO_PLAYGROUND_FETCH_FROM_GIT "${PICO_PLAYGROUND_FETCH_FROM_GIT}" CACHE BOOL "Set to ON to fetch copy of PICO EXTRAS from git if not otherwise locatable")
set(PICO_PLAYGROUND_FETCH_FROM_GIT_PATH "${PICO_PLAYGROUND_FETCH_FROM_GIT_PATH}" CACHE FILEPATH "location to download EXTRAS")

get_filename_component(PICO_PLAYGROUND_PATH "${PICO_PLAYGROUND_PATH}" REALPATH BASE_DIR "${CMAKE_BINARY_DIR}")
if (NOT EXISTS ${PICO_PLAYGROUND_PATH})
    message(FATAL_ERROR "Directory '${PICO_PLAYGROUND_PATH}' not found")
endif ()

set(PICO_PLAYGROUND_PATH ${PICO_PLAYGROUND_PATH} CACHE PATH "Path to the PICO EXTRAS" FORCE)

add_subdirectory(${PICO_PLAYGROUND_PATH} PICO_PLAYGROUND)